### ISSUE TITLE
Переосмылить материал лекции

### ISSUE THREAD

**Issue by egpro** [CypressMan/lecture2#1]
https://github.com/CypressMan/lecture2/blob/0691b4ca9073d77cd5e4dfdbe4d2fb88d0d6e988/2zadanie-lists.py#L10

Я же говорил, что там итерироваться по спискам НЕЛЬЗЯ!!!!

**Comment by CypressMan** [comment]
Исправил на enumerate

**Comment by CypressMan** [comment]
еще сделал с помощью zip
