### ISSUE TITLE
Учим матан

### ISSUE THREAD

**Issue by egpro** [CypressMan/lecture2#2]
https://github.com/CypressMan/lecture2/blob/0691b4ca9073d77cd5e4dfdbe4d2fb88d0d6e988/2zadanie-lists.py#L11

Есть более простое и лаконичное решение для проверки двух чисел на одинаковость знаков.

Читаем матан

**Comment by CypressMan** [comment]
if numbers[i] * numbers[i-1] > 0:
     print(numbers[i-1], numbers[i])

****
А если Numbers[i] = (-1) и Numbers[i] = 0?

**Comment by CypressMan** [comment]
Исправил на условие: если (произведение > 0) или (произведение = 0 и сумма > 0) то выводит элемент...
