### ISSUE TITLE
Что это такое?

### ISSUE THREAD

**Issue by egpro** [CypressMan/lecture2#3]
https://github.com/CypressMan/lecture2/blob/0691b4ca9073d77cd5e4dfdbe4d2fb88d0d6e988/6zadanie-function.py#L19

Вкурить материал лекции, хорошо подумать, продумать нормальный алгоритм валидации, почитать про встроенные функции в языке пайтон

**Comment by CypressMan** [comment]
Убрал списки символов.
Убрал циклы обрезания.
Убрал циклы нахождения элемента
Добавлены срезы по разделителю.
Добавлены поиск элементов с помощью регулярных выражений
